# Generated by Django 4.2.1 on 2023-06-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailaway', '0002_port_alter_sailaway_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('sailaways', models.ManyToManyField(blank=True, related_name='passengers', to='sailaway.sailaway')),
            ],
        ),
    ]
